### ISSUE TITLE
Allow injecting environment variables in yaml config just as in docker-compose.yml

### ISSUE THREAD

**Issue by kabirbaidhya** [leapfrogtechnology/chill#25]
I think we also need a way to inject environment variables into our `yml` config file just the way `docker-compose.yml` allows:

```yml
database:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    name: ${DATABASE_NAME}
```
