### ISSUE TITLE
Ability to provide HTTP Basic Auth params for each service

### ISSUE THREAD

**Issue by kabirbaidhya** [leapfrogtechnology/chill#41]
Some of the services could be protected with HTTP Basic Auth username/password. For instance test/dev servers which are not meant to allow public access. 
We need a way to send username/password for these kind of services like this:
```yml
services:
  -
    name: 'Dev Server'
    url: 'https://dev.myapp.com'
    auth:
      username: test
      password: test
```
